// Code generated by hertz generator.

package demo3

import (
	"context"

	demo3 "Demo3/biz/model/demo3"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo3.ApiReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo3.ApiResp)
	resp.RespBody = "hello, " + req.Name
	c.JSON(consts.StatusOK, resp)
}

// OtherMethod .
// @router /other [POST]
func OtherMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo3.OtherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo3.OtherResp)
	resp.Resp = "OtherMethod: " + req.Other
	c.JSON(consts.StatusOK, resp)
}
