// Code generated by hertz generator.

package demo3

import (
	"context"

	demo3 "Demo3/biz/model/demo3"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	"github.com/cloudwego/kitex/pkg/generic"
    "github.com/cloudwego/kitex/server/genericserver"
)

// NewMethod .
// @router /new [GET]
func NewMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo3.ApiReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	

	resp := new(demo3.ApiResp)

	c.JSON(consts.StatusOK, resp)
}
