// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	hello "Demo2/biz/router/hello"
	hello_example "Demo2/biz/router/hello/example"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	hello_example.Register(r)

	hello.Register(r)
}
